name: 'Docker Build with Cache and Slack'
description: 'Build Docker image with caching and optional Slack notifications'
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  context:
    description: 'Build context path'
    required: false
    default: '.'
  image-name:
    description: 'Docker image name'
    required: true
  tags:
    description: 'Docker image tags (comma-separated)'
    required: false
    default: 'latest'
  build-args:
    description: 'Build arguments (comma-separated KEY=VALUE pairs)'
    required: false
    default: ''
  registry:
    description: 'Docker registry (e.g., ghcr.io, docker.io, ECR)'
    required: false
    default: 'docker.io'
  registry-username:
    description: 'Registry username'
    required: false
  registry-password:
    description: 'Registry password'
    required: false
  aws-region:
    description: 'AWS region for ECR'
    required: false
  aws-access-key-id:
    description: 'AWS Access Key'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Key'
    required: false
  push:
    description: 'Push image to registry'
    required: false
    default: 'false'
  pre-build-script:
    description: 'Script to run before build'
    required: false
  post-build-script:
    description: 'Script to run after build'
    required: false

outputs:
  image-tag:
    description: 'Full image tag that was built'
    value: ${{ steps.set-outputs.outputs.image-tag }}
  digest:
    description: 'Image digest'
    value: ${{ steps.set-outputs.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Run pre-build script
      if: inputs.pre-build-script != ''
      shell: bash
      run: |
        echo "Running pre-build script..."
        ${{ inputs.pre-build-script }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure registry credentials
      id: registry-creds
      shell: bash
      run: |
        if [ -n "${{ inputs.aws-access-key-id }}" ]; then
          echo "Configuring ECR credentials..."
          REGION="${{ inputs.aws-region }}"
          
          # Get ECR authorization token
          RESPONSE=$(curl -s -X POST "https://api.ecr.${REGION}.amazonaws.com/" \
            -H "Content-Type: application/x-amz-json-1.1" \
            -H "X-Amz-Target: AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken" \
            -H "X-Amz-Date: $(date -u +%Y%m%dT%H%M%SZ)" \
            --aws-sigv4 "aws:amz:${REGION}:ecr" \
            --user "${{ inputs.aws-access-key-id }}:${{ inputs.aws-secret-access-key }}" \
            -d '{}')
          
          # Extract and decode token
          TOKEN=$(echo "$RESPONSE" | grep -o '"authorizationToken":"[^"]*"' | cut -d'"' -f4)
          DECODED=$(echo "$TOKEN" | base64 -d)
          
          USERNAME=$(echo "$DECODED" | cut -d: -f1)
          PASSWORD=$(echo "$DECODED" | cut -d: -f2)
          
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "::add-mask::$PASSWORD"
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT
        else
          echo "Using provided registry credentials..."
          echo "username=${{ inputs.registry-username }}" >> $GITHUB_OUTPUT
          echo "password=${{ inputs.registry-password }}" >> $GITHUB_OUTPUT
        fi

    - name: Login to Registry
      if: steps.registry-creds.outputs.username != '' && steps.registry-creds.outputs.password != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ steps.registry-creds.outputs.username }}
        password: ${{ steps.registry-creds.outputs.password }}

    - name: Prepare tags and build args
      id: prep
      shell: bash
      run: |
        TAGS=""
        IFS=',' read -ra TAG_ARRAY <<< "${{ inputs.tags }}"
        for tag in "${TAG_ARRAY[@]}"; do
          tag=$(echo "$tag" | xargs)
          if [ -n "$TAGS" ]; then
            TAGS="$TAGS,"
          fi
          REG="${{ inputs.registry }}"
          IMG="${{ inputs.image-name }}"
          TAGS="$TAGS${REG}/${IMG}:$tag"
        done
        echo "tags=$TAGS" >> $GITHUB_OUTPUT
        
        BUILD_ARGS=""
        if [ -n "${{ inputs.build-args }}" ]; then
          IFS=',' read -ra ARG_ARRAY <<< "${{ inputs.build-args }}"
          for arg in "${ARG_ARRAY[@]}"; do
            arg=$(echo "$arg" | xargs)
            BUILD_ARGS="$BUILD_ARGS --build-arg $arg"
          done
        fi
        echo "build-args=$BUILD_ARGS" >> $GITHUB_OUTPUT

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.prep.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build-args }}

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "image-tag=${{ steps.prep.outputs.tags }}" >> $GITHUB_OUTPUT
        echo "digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

    - name: Run post-build script
      if: inputs.post-build-script != ''
      shell: bash
      run: |
        echo "Running post-build script..."
        ${{ inputs.post-build-script }}
